name: Build and Push Docker image to ECR

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ECR_REPOSITORY: instagram_recipe_parser

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 135234974038.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        id: build-and-push
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to Amazon ECR
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Tag latest image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          docker tag ${{ secrets.ECR_REPOSITORY_URI }}/$ECR_REPOSITORY:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}/$ECR_REPOSITORY:latest
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest
